### ISSUE TITLE
Track en-IE versions of documents

### ISSUE THREAD

**Issue by LVerneyPEReN** [ambanum/OpenTermsArchive#225]
Hi,

So far, we are tracking the en-GB versions of the documents. However, Brexit might affect these versions, which might no longer be aligned with European reglementation.

See for instance this move by Facebook : https://www.ft.com/content/bde9c983-bfbd-4bb8-a524-2e93facfe36b. Few days ago, a change in the Microsoft policies (https://github.com/ambanum/CGUs-versions/commit/151d6e26f082fe38d22a00215a46c3d5f56d5953) with no other changes than changing from british english to american english tends as well to indicate that UK terms might get aligned on US terms soon.

I understand we want to track English versions of documents as main elements, to ease comparison with foreign services and prevents translations artifacts. I suggest we move from en-GB to en-IE (Ireland) as this last one is ensured to be in English **and** under European law.

Best,

**Comment by LVerneyPEReN** [comment]
Is there some place to track the current status of documents and which ones need a review / updating?

**Comment by MattiSG** [comment]
We moved away from one single repository of declarations to having multiple instances. This issue referred to a time when [`contrib-declarations`](https://github.com/OpenTermsArchive/contrib-declarations/) was the only source of documents to be tracked. Since then, several instances have been created. Contributors are welcome to create their own ones, each focused on a specific scope (by industry, by jurisdiction, by language…). We for example have a French-focused instance, [`france`](https://github.com/OpenTermsArchive/france-declarations/).

In order to track `en-gb` or `en-ie` instances, feel free to suggest changes to `contrib` and / or to create a new instance focused on the given scope. We will be happy to help with setting up the instance, as has been done with now several partners 🙂

> Is there some place to track the current status of documents and which ones need a review / updating?

Each instance tracks its own documents status with GitHub issues and pull requests (example with [`france`](https://github.com/OpenTermsArchive/france-declarations/). Beyond human identification, a GitHub bot opens and closes them automatically as technical issues (timeout, 403…) are encountered 🙂

 - - - -

Since this repository is now explicitly focused on the Core Open Terms Archive engine and not on tracking specific documents or defining the scope of tracked documents, I will close this issue 🙂
