### ISSUE TITLE
Clean Reddit Privacy Policy

### ISSUE THREAD

**Issue by vviers** [ambanum/OpenTermsArchive#227]
[Reddit Privacy Policy](https://raw.githubusercontent.com/ambanum/CGUs-versions/master/Reddit/Privacy%20Policy.md) is in a table format. The content in the table is not parsed correctly (e.g. <br> tags remain).

**Comment by martinratinaud** [comment]
I will have a look at what's going on tomorrow

**Comment by MattiSG** [comment]
The [last version](https://github.com/ambanum/OpenTermsArchive-versions/blob/master/Reddit/Privacy%20Policy.md), while indeed not perfectly parsed, does not seem to be unreadable.

If you have a use case that needs this policy document to be better formatted, please reopen this issue in https://github.com/OpenTermsArchive/services-all. We migrated the declarations to that other repository, in order to clarify the distinction between the Open Terms Archive engine and the documents themselves, which can be maintained by different entities 🙂 You can find more information on that change in #684.
