### ISSUE TITLE
Google l10n and i18n

### ISSUE THREAD

**Issue by LVerneyPEReN** [ambanum/OpenTermsArchive#238]
Hi,

Apparently Google has two query parameters for l10n and i18n, namely `hl` (for locale) and `gl` (for country).

There was issues recently with rapid and unexpected switching between two geographical regions on Google terms (possibly due to IP geolocation or something like this). This seems solved at the moment, so just noting this here in case the issue comes back.

It might be solved by passing something such as `gl=ie` in the URL.

As an example, https://play.google.com/store/apps/details?id=com.hulu.plus&hl=fr&gl=us and https://play.google.com/store/apps/details?id=com.hulu.plus&hl=fr&gl=fr makes the distinction between these parameters clean in their footer.

Best,

**Comment by clementbiron** [comment]
> As an example, https://play.google.com/store/apps/details?id=com.hulu.plus&hl=fr&gl=us and https://play.google.com/store/apps/details?id=com.hulu.plus&hl=fr&gl=fr makes the distinction between these parameters clean in their footer.

It works perfectly in this example, thanks for sharing.

I tried to add `gl=ie` parameter to some Google documents already tracked in OTA without being able to know if it works since it doesn't cause any graphical or textual changes.

- Google Drive ToS : https://www.google.com/drive/terms-of-service/?hl=en_GB&gl=ie
- Google Chat Acceptable Use Policy : https://support.google.com/chat/answer/9257382?hl=en-GB&gl=ie
- Google Cloud Platform Terms of Service : https://cloud.google.com/terms/?hl=en-GB&gl=ie

I haven't found any documentation about `gl=ie` param do you know if there is any?


Sorry for this very late reply. 🙀

**Comment by clementbiron** [comment]
I saw the change in the footer of play.google.com/store, it is very explicit that the parameter works. But it's not easy to know if it works when there is no visible change.

In the next weeks we will work on the implementation of the possibility to follow documents in several languages and jurisdictions (with @MattiSG and @Ndpnt). We will have to modify every documents to fill this informations and we will probably use `hl`and `gl` parameter for Google documents.

Thanks again !

**Comment by MattiSG** [comment]
Thanks again @LVerneyPEReN for this useful piece of information! 👍

As explained in https://github.com/ambanum/OpenTermsArchive/issues/225#issuecomment-1108228208, this trick is very useful for individual instances and has been implemented in some of them (for example `france`). There are no plans to include it in the core engine, which aims at staying as generic as possible. I will thus close this issue from this repository 🙂
