### ISSUE TITLE
Refactor explicit exclusion of `/home/debian/cgus/` as argument

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#665]
As seen in https://github.com/ambanum/OpenTermsArchive/commit/06bfb903cdeba00662ab13cdc2a1617248e6f0c1, an additional parameter is given to `npm start` in production by `forever`. This folder name is currently hardcoded and is thus brittle and installation-dependent.
This should at least be documented, and if possible the argument removed altogether.

**Comment by martinratinaud** [comment]
The problem exists because of the way we are using `forever`

we are launching `forever start -m 10 -a --uid "{{ app }}" -c "npm run start:scheduler:prod" ./`
Note the `./` at the end.
This will in fact launch
`cross-env NODE_ENV=production node --max-http-header-size=32768 src/index.js --schedule "/home/debian/cgus/"`

With `forever start -m 10 -a --uid "{{ app }}" -c "npm run start:scheduler:prod" .`
It would launch `cross-env NODE_ENV=production node --max-http-header-size=32768 src/index.js --schedule "/home/debian/cgus"` (no trailing slash)

i'm currently checking how to bypass that.
If you have any idea @Ndpnt @MattiSG you're welcome

**Comment by MattiSG** [comment]
`pm2` [exponential backoff](https://pm2.keymetrics.io/docs/usage/restart-strategies/#exponential-backoff-restart-delay) is great, I had it in production for a while and it served me well 👍
