### ISSUE TITLE
Deploy automatically updates to the service declarations

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#716]
Following #708, changes to the service declarations are not deployed automatically anymore.

Merges to `OTA/services-all` should trigger a deployment.

If this is not possible, a check-changes-and-deploy workflow should be [scheduled](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule).

**Comment by Ndpnt** [comment]
See https://github.com/actions/checkout/issues/24

**Comment by martinratinaud** [comment]
Just because I though it could be easy using what I already did, I tried with those branches

https://github.com/ambanum/OpenTermsArchive/commit/327086033d2b0cdc41094d772ec40d693915139b
https://github.com/OpenTermsArchive/services-all/commit/d6578c848fd14d6a959991f005d232f51647c5fb


But unfortunately it does not work

The workflow called, even though is on another repository, use the current git

**Comment by martinratinaud** [comment]
I finally ended up cloning the repo directly in `services-all` github actions.

I believe https://github.com/ambanum/OpenTermsArchive/pull/712 is not necesary anymore @Ndpnt ?

Here is the pull request on `services-all` https://github.com/OpenTermsArchive/services-all/pull/235

**Comment by Ndpnt** [comment]
Fixed by OpenTermsArchive/services-all#235

**Comment by MattiSG** [comment]
Unfortunately, as evidenced by [this run](https://github.com/OpenTermsArchive/services-all/runs/4471299361), this does not work.

**Comment by MattiSG** [comment]
Should be fixed in OpenTermsArchive/services-all#272. Try updating a service in `services-all` once that PR has been merged.
