### ISSUE TITLE
Clean CDiscount Commercial Terms 

### ISSUE THREAD

**Issue by trujilloelsa** [ambanum/OpenTermsArchive#719]
https://github.com/ambanum/OpenTermsArchive-versions/commit/5469583 
Introduces noise by adding and erasing some " ' ".

https://github.com/ambanum/OpenTermsArchive-versions/commit/be4ea7857c42c4d19c7bc385deaa5b3b57262f3f

**Comment by MattiSG** [comment]
Thanks @trujilloelsa!

If I understood correctly what you explained this is an intentional change by the service provider, acting as a watermark 🙂

Thus, this is not “noise” in the sense that it should be removed, it is a non-significant change. We need to explore more this category of changes before we can decide how to treat them properly.

In any case, please use https://github.com/OpenTermsArchive/services-all for any noise report. We indeed migrated the declarations to that other repository, in order to clarify the distinction between the Open Terms Archive engine and the documents themselves, which can be maintained by different entities 🙂 

Thanks again for your report!
