### ISSUE TITLE
Email notifications are sent with wrong destination URLs

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#757]
Email notifications for instances that are not `services-all` do not have a proper link.

### Example

The link is https://github.com/ambanum/OpenTermsArchive-versions/commit/2eeb037
and should be https://github.com/OpenTermsArchive/france-versions/commit/2eeb037

```
Brice just updated their Commercial Terms
 
We recorded a new version of Brice's Commercial Terms
 
If the button does not work, copy the following address into your browser address bar:
https://github.com/ambanum/OpenTermsArchive-versions/commit/2eeb037
```

**Comment by martinratinaud** [comment]
For now, what happens is that the mail template to be used is taken from the configuration file and the program sends 3 variables (SHA, SERVICE_PROVIDER_NAME and DOCUMENT_TYPE) to customize it.

See https://github.com/ambanum/OpenTermsArchive/blob/master/src/notifier/index.js#L36

So we have two ways to handle this here

1. modify the code so that instead of sending only the SHA, it sends the whole url

This implies having a new entry in the config  such as `notifier.versionsBaseUrl` and modifying the existing template so that it handles nicely this.
This would also make it easier to change if we ever have our own website showing the changes (which would be needed if mongo was used for versions)

2. create another template and modifier the `notifier.sendInBlue.updateTemplateId` for each instance

This would be the easiest and would enable the possibility to have different layouts depending on the instance (logo UFC for example)

As we are the only ones using this at the moment i would go for option 2.
But I think we should end up with option 1 AND option 2 so that we can configure both the whole url AND the layout

@MattiSG @Ndpnt what do you prefer?

**Comment by Ndpnt** [comment]
For now I prefer option 2 for the same reason as you.

**Comment by martinratinaud** [comment]
and in fact @Ndpnt I also think the easiest would in fact to remove the notifier from those instances.

As there is no way to subscribe to them.

The code, would just have to be updated to 

```
  if (process.env.NODE_ENV === 'production' && config.get("notifier.sendInBlue")) {
    archivist.attach(new Notifier(archivist.serviceDeclarations));
  }
```

or `notifier.enabled`

**Comment by martinratinaud** [comment]
And so a last change of mind

What I'm about to implement is

- [ ] Create an update list for each instance
- [ ] remove the administratorsList (if you want to receive updates, better be in the same list as others in case something does not work
- [ ] Create 1 template per instance
- [ ] Map the right list and templates ids in the config files

**Comment by martinratinaud** [comment]
PR ready for review @Ndpnt
