### ISSUE TITLE
Unify repository naming

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#794]
- `services-…` → `declarations-…`
- Prefix with ID instead of suffixing.
- `experimental` → `experiment` in ops config.
- Document repository naming pattern in CONTRIBUTING.
- `all` → `contrib` 
- `ambanum/OpenTermsArchive-versions` → `OpenTermsArchive/contrib-versions`

**Comment by martinratinaud** [comment]
Before merging, some actions are necessary

**NOTE** I propose to move those folders instead of removing them to save the time of redownloading when deploying

- [ ] rename services-all to contrib-declarations
- [ ] rename ambanum/OpenTermsArchive-versions to OpenTermsArchive/contrib-versions
- [ ] rename ambanum/OpenTermsArchive-snapshots to OpenTermsArchive/contrib-snapshots
- [ ] rename declarations-france to france-declarations with snapshots and versions
- [ ] rename declarations-france-elections to france-declarations-elections with snapshots and versions
- [ ] rename services-dating to dating-declarations with snapshots and versions

- [ ] stop OTA on `services-all` and rename folders
```
mv ota-services-all ota-contrib-declarations
mv ota-snapshots ota-contrib-snapshots
mv ota-versions ota-contrib-versions
```

- [ ] stop OTA on `dating` and rename folders 
```
mv ota-versions-dating ota-dating-versions
mv ota-snapshots-dating ota-dating-snapshots
mv ota-services-dating ota-dating-declarations
```

- [ ] stop OTA on `france` and rename folders 
```
mv ota-versions-france ota-france-versions
mv ota-snapshots-france ota-france-snapshots
mv ota-services-france ota-france-declarations
```

- [ ] stop OTA on `france-elections` and rename folders 
```
mv ota-versions-france-elections ota-france-elections-versions
mv ota-snapshots-france-elections ota-france-elections-snapshots
mv ota-services-france-elections ota-france-elections-declarations
```

- [ ] merge https://github.com/OpenTermsArchive/declarations-france/pull/318
- [ ] merge https://github.com/OpenTermsArchive/services-dating/pull/77
- [ ] merge https://github.com/OpenTermsArchive/declarations-france-elections/pull/86
- [ ] no PR needed for services-all (did not find any reference to a github account name)


## On Local

You will need to

- rename your local folder from `services-all` to `contrib-declarations`
- rename your local folder from `services-dating` to `dating-declarations`
- rename your local folder from `declarations-france-elections` to `france-elections-declarations`
- rename your local folder from `declarations-france` to `france-declarations`

Do all at once
```
mv services-all contrib-declarations
mv services-dating dating-declarations
mv declarations-france-elections france-elections-declarations
mv declarations-france france-elections

```

**Comment by martinratinaud** [comment]
@MattiSG I prepared everything but still need

- admin rights on OpenTermsArchive organization
- an explanation on experimental → experiment in ops config. as I don't find any string like that in it (maybe @Ndpnt knows)

**Comment by martinratinaud** [comment]
@Ndpnt @clementbiron @MattiSG 
I made the changes on all repos
I think you should all review in search of a typo :-)
I think it should not be long nor be difficult

I will try to deploy all this on monday morning if you validated

**Comment by MattiSG** [comment]
> admin rights on OpenTermsArchive organization

You're an owner :wink:

Todo too:

- [ ] Rename the [`services-all` team](https://github.com/orgs/OpenTermsArchive/teams/services-all) to `contrib`

As for renaming on the instances, I am not sure I see the current added value of having each local folder having a different name… I find it more confusing than anything. Since we need to intervene in any case, I would be in favour of unifying all the folder names to `declarations`, `snapshots` and `versions`, and let the name of the instance distinguish. Thus, on every server we would have those folders plus the `OpenTermsArchive` repo clone, and we could default to these names in the ops config in order to decrease significantly the complexity of defining a new instance 🙂

**Comment by martinratinaud** [comment]
I like it better also to have `declarations, `snapshots` and `versions` folders

To make it possible to deploy 2 instances on the same server though (for experiments for example), I would either
- use the name of the instance (i.e. `dating`, `france`, `contrib`) in the path created

/home/{{ ansible_user }}/{{ ota_app_name }} -> /home/{{ ansible_user }}/{{ instance_name }}/{{ ota_app_name }}

- declare you own main folder ``

/home/{{ ansible_user }}/{{ ota_app_name }} -> /home/{{ ansible_user }}/{{ instance_directory }}/{{ ota_app_name }}

**Comment by martinratinaud** [comment]
@Ndpnt @MattiSG Just added this https://github.com/ambanum/OpenTermsArchive/pull/808 to be reviewed before I can merge

**Comment by Ndpnt** [comment]
I'm in favor of `none of them, we will always deploy one instance on one server` for now.

**Comment by MattiSG** [comment]
Thanks @martinratinaud. I'm in favour of keeping the current ability to override folder names on a per-instance basis, with a default value to `declarations`, `snapshots` and `versions`: in most cases, we will not define anything and will assume one instance per server; and in edge cases, we can specify the names 🙂
