### ISSUE TITLE
In declarations, testing specific file fails if another file has errors

### ISSUE THREAD

**Issue by Amustache** [ambanum/OpenTermsArchive#823]
Within a `<>-declarations` instance, if I have two files `A.json` and `B.json`, if I try to test for `A.json` but `B.json` has errors (i.e., not in a valid JSON format as of RFC 8259), the whole process fails. E.g.:

![image](https://user-images.githubusercontent.com/5108539/161986763-bfb69831-8f7b-4826-bda5-b9c1e6e2b094.png)

The same applies when trying to test all files, the whole process fails. E.g.:

![image](https://user-images.githubusercontent.com/5108539/161986989-045bb35a-a049-41e0-b799-49cdc2caf04c.png)

**Comment by Ndpnt** [comment]
Hi @Amustache and thanks for opening this issue. 
The first problem you describe should be fixed by https://github.com/ambanum/OpenTermsArchive/pull/835. 
For the second one, the behavior is the expected one: when testing all declarations, if one of them is malformed, the validation should fail. It could be improved by running tests for all valid declarations and failing only for malformed ones, but this involves a lot of work on how validation tests are generated and for now I think the current implementation with the #835 fix is a good compromise. Do you agree with this?

**Comment by MattiSG** [comment]
Thank you very much @Amustache for having reported this issue so clearly and @Ndpnt for having fixed it 👍

I understand that the reported issue has been fixed, and that the second part would be an improvement that is currently not worth investing in. The way to implement it would be to run two separate test suites, one checking for malformed files, and a second one loading only the files that are properly formed. This is not an improvement the core team currently has availability for. I will thus close this issue 🙂

If some contributor wants to open a PR with the changes mentioned above, they are welcome to! 😃
